geekshop/authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$',
            authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>/", basketapp.basket_remove, name="remove"),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path("", mainapp.main, name="main"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("contact/", mainapp.contact, name="contact"),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path('', include('social_django.urls', namespace='social')),
    path("order/", include("ordersapp.urls", namespace="order")),
]

if settings.DEBUG:
    import debug_toolbar
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

    # urlpatterns += static(settings.MEDIA_URL,
    #  document_root=settings.MEDIA_ROOT)

geekshop/basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product
from django.utils.functional import cached_property


class BasketQuerySet(models.QuerySet):

    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity += object.quantity
            object.product.save()
        super(BasketQuerySet, self).delete(*args, **kwargs)


class Basket(models.Model):
    objects = BasketQuerySet.as_manager()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="basket"
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(
        verbose_name="количество", default=0)
    add_datetime = models.DateTimeField(
        verbose_name="время", auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.pk:
            basket_item = Basket.objects.filter(pk=self.pk)
            self.product.quantity -= self.quantity - \
                basket_item[0].quantity
        else:
            self.product.quantity -= self.quantity
        self.product.save()
        super(self.__class__, self).save(*args, **kwargs)

    @cached_property
    def get_items_cached(self):
        return Basket.objects.filter(user=self.user).select_related()

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        _items = self.get_items_cached
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    @property
    def total_cost(self):
        _items = self.get_items_cached
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

geekshop/basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import F


@login_required
def basket(request):
    title = "корзина"
    basket_items = Basket.objects.filter(user=request.user).order_by(
        "product__category"
    )

    context = {
        "title": title,
        "basket_items": basket_items,
    }

    return render(request, "basketapp/basket.html", context)


@login_required
def basket_add(request, pk):
    if "login" in request.META.get("HTTP_REFERER"):
        return HttpResponseRedirect(reverse("products:product", args=[pk]))
    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity = F('quantity') + 1
    basket.save()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

geekshop/basketapp/templates/basketapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    {% block title %}
      {{ title|title }}
    {% endblock %}
  </title>
  {% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
  {% endblock %}
  {% block js %}
  {% endblock %}
</head>
<body>
  <div class="basket_container">        
    <div class="h2 text-center head">
      Ваша корзина, 
      {% if user.first_name %}
        {{ user.first_name|title}}
      {% else %}
        Пользователь
      {% endif %}
    </div>
            
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

geekshop/basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}
{% load static %}

{% block content %}
  <div class="basket_list">
  {% for item in basket_items %}
    <div class="basket_record">
      <img src="/media/{{ item.product.image }}" 
           alt="{{ item.product.main_desc }}">
      <span class="category_name">{{ item.product.category.name }}</span> 
      <span class="product_name">{{ item.product.name }}</span>
      <span class="product_price">{{ item.product.price }}&nbspруб</span>
      <input type="number" name="{{ item.pk }}" 
                           min="0" 
                           value="{{ item.quantity }}">
      <span class="product_cost">{{ item.cost }}&nbspруб</span>
      <button class="btn btn-round">
        <a href="{% url 'basket:remove' item.pk %}" class="">
          удалить
        </a>
      </button>
    </div>
  {% endfor %}

  {% if basket_items %}
    <div class="basket_summary">
      В корзине {{ basket_items.0.total_quantity }} товаров общей стоимостью
                {{ basket_items.0.total_cost }} руб
    </div>
  {% endif %}
        
    <button class="btn btn-round">
      <a href="{% url 'main' %}">на главную</a>
    </button>
  </div>
{% endblock %}