geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = "adminapp"

urlpatterns = [
    path("users/create/", adminapp.UserCreateView.as_view(), name="user_create"),
    path("users/read/", adminapp.UsersListView.as_view(), name="users"),
    path(
        "users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="user_update"
    ),
    path(
        "users/delete/<int:pk>/", adminapp.UserDeleteView.as_view(), name="user_delete"
    ),
    path(
        "categories/create/",
        adminapp.ProductCategoryCreateView.as_view(),
        name="category_create",
    ),
    path("categories/read/", adminapp.CategoriesListView.as_view(), name="categories"),
    path(
        "categories/update/<int:pk>/",
        adminapp.ProductCategoryUpdateView.as_view(),
        name="category_update",
    ),
    path(
        "categories/delete/<int:pk>/",
        adminapp.ProductCategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path(
        "products/create/category/<int:pk>/",
        adminapp.ProductCreateView.as_view(),
        name="product_create",
    ),
    path("products/read/category/<int:pk>/", adminapp.products, name="products"),
    path(
        "products/read/category/<int:pk>/page/<int:page>/",
        adminapp.products,
        name="page",
    ),
    path(
        "products/read/<int:pk>/",
        adminapp.ProductDetailView.as_view(),
        name="product_read",
    ),
    path("products/update/<int:pk>/", adminapp.product_update, name="product_update"),
    path(
        "products/delete/<int:pk>/",
        adminapp.ProductDeleteView.as_view(),
        name="product_delete",
    ),
]

geekshop/authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$',
            authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path("", mainapp.main, name="main"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("contact/", mainapp.contact, name="contact"),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path('', include('social_django.urls', namespace='social')),
    path("order/", include("ordersapp.urls", namespace="order")),
]

if settings.DEBUG:
    import debug_toolbar
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

    # urlpatterns += static(settings.MEDIA_URL,
    #  document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from mainapp.models import ProductCategory
from authapp.forms import ShopUserEditForm
from mainapp.models import Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False,
                                  min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        # fields = "__all__"
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

geekshop/adminapp/views.py
from django.shortcuts import render, get_object_or_404
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import (
    ShopUserAdminEditForm,
    ProductCategoryEditForm,
    ProductEditForm,
)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection
from django.db.models import F


class UsersListView(ListView):
    model = ShopUser
    template_name = "adminapp/users.html"

    def get_queryset(self):
        return ShopUser.objects.order_by(
            "-is_active", "-is_superuser", "-is_staff", "username"
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "админка/пользователи"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class UserCreateView(CreateView):
    model = ShopUser
    template_name = "adminapp/user_update.html"
    success_url = reverse_lazy("admin:users")
    form_class = ShopUserRegisterForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "пользователи/создание"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = "adminapp/user_update.html"
    form_class = ShopUserAdminEditForm

    def get_success_url(self):
        return reverse_lazy("admin:user_update", args=[self.kwargs["pk"]])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "пользователи/редактирование"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = "adminapp/user_delete.html"
    success_url = reverse_lazy("admin:users")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "пользователи/удаление"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CategoriesListView(ListView):
    model = ProductCategory
    template_name = "adminapp/categories.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "админка/категории"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "категории/создание"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    form_class = ProductCategoryEditForm
    #fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "категории/редактирование"
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.\
                    update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE',
                                   connection.queries)
        return super().form_valid(form)

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = "adminapp/category_delete.html"
    success_url = reverse_lazy("admin:categories")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "категории/удаление"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk, page=1):
    title = "админка/продукт"

    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by("name")
    paginator = Paginator(products_list, 2)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        "title": title,
        "category": category,
        "objects": products_paginator,
    }

    return render(request, "adminapp/products.html", context)


class ProductCreateView(CreateView):
    model = Product
    template_name = "adminapp/product_update.html"
    success_url = reverse_lazy("admin:products")
    fields = "__all__"

    def get_initial(self):
        initial = super().get_initial()
        initial["category"] = self.kwargs["pk"]
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "продукт/создание"
        context["category"] = get_object_or_404(
            ProductCategory, pk=self.kwargs["pk"])
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductDetailView(DetailView):
    model = Product
    template_name = "adminapp/product_read.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "продукт/подробнее"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = "продукт/редактирование"

    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        edit_form = ProductEditForm(
            request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(
                reverse("admin:product_update", args=[edit_product.pk])
            )
    else:
        edit_form = ProductEditForm(instance=edit_product)

    context = {
        "title": title,
        "form": edit_form,
        "category": edit_product.category,
    }

    return render(request, "adminapp/product_update.html", context)


class ProductDeleteView(DeleteView):
    model = Product
    template_name = "adminapp/product_delete.html"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy("admin:products", args=[self.object.category.pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "продукт/удаление"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)
        db_profile_by_type(sender, 'UPDATE', connection.queries)

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
    <div class="admin_container">        
      <div class="h2 text-center head">
        Админка
      </div>
      {% block menu %}
        <div class="admin_menu">
          {% include 'adminapp/includes/inc_menu.html' %}
        </div>
      {% endblock %}
             
      {% block content %}
      {% endblock %}
    </div>
  </body>
  </html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href={% url 'admin:category_create' %}>
        новая категория
      </a>
    </button>
		
    {% for object in object_list %}
      <div class="category_record {% if not object.is_active %} not_active {% endif %}">
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href={% url 'admin:products' object.pk %}>
              товары категории
            </a>
          </button>
          <button>
            <a href={% url 'admin:category_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:category_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="category_delete">
    Уверены, что хотите удалить категорию {{ category_to_delete.name }} ?
    <form action="{% url 'admin:category_delete' category_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:categories' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="product_delete">
    Уверены, что хотите удалить товар {{ object.name }} ?
    <form action="{% url 'admin:product_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:products' object.category.pk %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ object.category.name|title }} / 
                     {{ object.name|title }}</strong> 
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
         alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price|rubles }}</p>
      <b>количество</b>
      <p>{{ object.quantity|pieces }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'admin:product_update' object.pk %}>
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'admin:product_delete' object.pk %}>
            удалить
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'admin:products' object.category.pk %}>
            назад
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>краткая информация</b>
      <p>{{ object.main_desc }}</p>
      <br><br>
      <b>подробная информация</b>
      <p>{{ object.description }}</p>
    </div>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:products' category.pk %}">
      к списку товаров
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin:product_create' category.pk %}>
        новый продукт
      </a>
    </button>
		
    <div class="paginator">
      {% if objects.has_previous %}
        <a href="{% url 'admin:page' category.pk objects.previous_page_number %}">
          <
        </a>
      {% endif %}
      <span class="current">
        страница {{ objects.number }} из 
        {{ objects.paginator.num_pages }}
      </span>
      {% if objects.has_next %}
        <a href="{% url 'admin:page' category.pk objects.next_page_number %}">
          >
        </a>
      {% endif %}
    </div>

    {% for object in objects %}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img 
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'admin:product_read' object.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price|rubles }}</p>
          <b>количество</b>
          <p>{{ object.quantity|pieces }}</p>
        </div>
        <div class="product_desc">
          {{ object.main_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ object.username }} 
    {% if object.first_name %}
      ({{ object.first_name|title }}</b>
      {% if object.last_name %}
        {{ object.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin:user_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href={% url 'admin:user_create' %}>
        новый пользователь
      </a>
    </button>
    {% for object in object_list %}
      <div 
       class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img 
          src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
          alt="{{ object.username }}">
        <div class="user_role">
          {% if object.is_superuser %}
            администратор
          {% else %}
            пользователь
          {% endif %}
          <button>
            <a href={% url 'admin:user_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:user_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="user_name">
          <p><strong>{{ object.username }}</strong></p>
	    <p>
            {% if object.first_name %}
              <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                  <p>{{ object.last_name|title }}</p>
                {% endif %}
            {% endif %}
          </p>
        </div>
        <div class="user_age">
          age:<br>
          {{ object.age }} лет
        </div>
        <div class="user_email">
          email:<br>
          {{ object.email }}
        </div>
        <div class="user_lastlogin">
          logged:<br>
          {{ object.last_login }}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}