geekshop/authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$',
            authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>/", basketapp.basket_remove, name="remove"),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path("", mainapp.main, name="main"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("contact/", mainapp.contact, name="contact"),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path('', include('social_django.urls', namespace='social')),
    path("order/", include("ordersapp.urls", namespace="order")),
]

if settings.DEBUG:
    import debug_toolbar
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

    # urlpatterns += static(settings.MEDIA_URL,
    #  document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = "mainapp"

urlpatterns = [
    path("", mainapp.products, name="index"),
    path("category/<int:pk>/", mainapp.products, name="category"),
    path("category/<int:pk>/page/<int:page>/", mainapp.products, name="page"),
    path("product/<int:pk>/", mainapp.ProductView.as_view(), name="product"),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=100, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name="активна", default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(verbose_name="имя продукта", max_length=100)
    main_desc = models.CharField(
        verbose_name="краткое описание продукта", max_length=60, blank=True
    )
    description = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(
        verbose_name="цена продукта", max_digits=8, decimal_places=2, default=0
    )
    image = models.ImageField(
        verbose_name="изображение продукта", upload_to="products_images", blank=True
    )
    quantity = models.PositiveIntegerField(
        verbose_name="количество товара на складе", default=0
    )
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(verbose_name="активен", default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
import json
import os
from django.shortcuts import render
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
from basketapp.models import Basket
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.detail import DetailView
from django.conf import settings
from django.core.cache import cache


links_menu = [
    {"href": "main", "name": "домой"},
    {"href": "products:index", "name": "продукты"},
    {"href": "contact", "name": "контакты"},
    {"href": "basket:view", "name": "корзина"},
]

catalog = [
    {
        "name": "Прекрасный стул",
        "description": "Прекрасный выбор!",
        "img": "img/product-1.jpg",
    },
    {
        "name": "Удобные стулья",
        "description": "Замечательное удобство!",
        "img": "img/product-2.jpg",
    },
    {
        "name": "Стул повышенного качества",
        "description": "Не оторваться",
        "img": "img/product-3.jpg",
    },
]


def main(request):
    products = Product.objects.all().select_related('category')[:3]
    return render(
        request,
        "mainapp/index.html",
        context={"links_menu": links_menu,
                 "catalog": products, "title": "магазин"},
    )


def get_hot_product():
    products = Product.objects.filter(is_active=True)
    if products:
        return random.sample(list(products), 1)[0]
    else:
        return None


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(
        pk=hot_product.pk
    )[:3]

    return same_products


def get_categories():
    if settings.LOW_CACHE:
        KEY = 'all_categories'
        categories = cache.get(KEY)
        if not categories:
            categories = ProductCategory.objects.filter(is_active=True)
            cache.set(KEY, categories)
            return categories
    else:
        return ProductCategory.objects.filter(is_active=True)


def products(request, pk=None, page=1):

    prod_menu = get_categories()

    if pk is not None:
        if pk == 0:
            category = {"pk": 0, "name": "все"}
            products = Product.objects.filter(
                is_active=True, category__is_active=True
            ).order_by("price")

        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(
                category__pk=pk, is_active=True, category__is_active=True
            ).order_by("price")

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        return render(
            request,
            "mainapp/products_list.html",
            context={
                "title": "каталог",
                "links_menu": links_menu,
                "category": category,
                "products": products_paginator,
                "prod_menu": prod_menu,
            },
        )

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    return render(
        request,
        "mainapp/products.html",
        context={
            "links_menu": links_menu,
            "catalog": same_products,
            "title": "каталог",
            "prod_menu": prod_menu,
            "hot_product": hot_product,
        },
    )


def contact(request):
    return render(
        request,
        "mainapp/contact.html",
        context={"links_menu": links_menu, "title": "контакты"},
    )


class ProductView(DetailView):
    model = Product
    template_name = "mainapp/product.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "продукты"
        context["links_menu"] = links_menu
        context['prod_menu'] = get_categories()
        return context

geekshop/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	{% block title %}
    <title>{{ title|title }}</title>
    {% endblock title %}
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock css %}
    {% block js %}
       <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
       <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}

	
</head>
<body>
	{% block container %}
    {% endblock container %}

	{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock footer %}	
	
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
	<div class="container">
		<div class="hero">
			<div class="header clearfix">
				<a href="{% url 'main' %}" class="logo"></a>
				{% include 'mainapp/includes/inc_menu.html' %}
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>	
{% endblock container %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
	<div class="container">
		<div class="slider">
			<div class="header clearfix">
				<a href="{% url 'main' %}" class="logo"></a>
				{% include 'mainapp/includes/inc_menu.html' %}
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for prod in catalog %}
				<div class="block">
					<a href="{% url 'products:product' prod.pk %}"><img src="/media/{{ prod.image }}" alt="{{ prod.main_desc }}">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="">
							<h3>{{ prod.category.name }}</h3> 
							<h4>{{ prod.name }}</h4>
							<p> {{ prod.description }} </p>
						</div>
					</a>
				</div>
				{% endfor %}	
			</div>
		</div>
		
		<div class="clr"></div>

	</div>
{% endblock container %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
<div class="hero-white">
  <div class="header clearfix">
      <a href="{% url 'main' %}" class="logo"></a>
      {% include 'mainapp/includes/inc_menu.html' %}
  </div>
</div>
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}" 
               alt="{{ object.main_desc }}">
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ object.name }}</h3>
        <br>
        <p class="price"> {{ object.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' object.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ object.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>

  {% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">
				<a href="{% url 'main' %}" class="logo"></a>
				{% include 'mainapp/includes/inc_menu.html' %}
				<a href="#" class="search"></a>
			</div>
		</div>

		<div class="details">
			{% include 'mainapp/includes/inc_categories_menu.html' %}
			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
					  <img src="/media/{{ hot_product.image }}">
					</div>
					<div class="slider-control">
					  <div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					  </div>
					  <div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					  </div>
					  <div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					  </div>
					</div>
				  </div>
			
				  <div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price">{{ hot_product.price }} <span>руб</span></p>
					<a href="{% url 'products:product' hot_product.pk %}" class="red-button">
					  заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
					  {{ hot_product.description }} 
					</div>
				</div>
			</div>			

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for prod in catalog %}
					<div class="block">
						<a href="{% url 'products:product' prod.pk %}"><img src="/media/{{ prod.image }}" alt="{{ prod.main_desc }}">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="">
								<h3>{{ prod.category.name }}</h3>
								<h4>{{ prod.name }}</h4>
								<p> {{ prod.description }} </p>
							</div>
						</a>
					</div>
					{% endfor %}

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>	
{% endblock container %}

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="container">
        <div class="hero-white">
            <div class="header clearfix">
                <a href="{% url 'main' %}" class="logo"></a>
                {% include 'mainapp/includes/inc_menu.html' %}
                <a href="#" class="search"></a>
                <a href="#" class="basket"></a>
            </div>
        </div>
  <div class="details">
      {% include 'mainapp/includes/inc_categories_menu.html' %}

    <div class="products_list">
      <div class="title clearfix">
        <h2>
          Категория: "{{ category.name|title }}"
        </h2>
        <div class="paginator">
          {% if products.has_previous %}
            <a href="{% url 'products:page' category.pk products.previous_page_number %}">
              <
            </a>
          {% endif %}
          <span class="current">
            страница {{ products.number }} из {{ products.paginator.num_pages }}
          </span>
          {% if products.has_next %}
            <a href="{% url 'products:page' category.pk products.next_page_number %}">
              >
            </a>
          {% endif %}
        </div>
      </div>
      </div>

      <div class="category-products clearfix">
        {% for product in products %}
          <div class="block">
            <a href="{% url 'products:product' product.pk %}">
              <img src="/media/{{ product.image }}" alt="{{ product.main_desc }}">
              <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                  <h4>{{ product.name }}</h4>
                  <p>{{ product.description }}</p>
              </div>
            </a>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>

  <div class="clr"></div>

{% endblock %}